spring.application.name=dadata_gateway
dadata.base-url=${DADATA_BASE_URL}
dadata.auth-token=${DADATA_AUTH_TOKEN}
dadata.endpoints.suggest-address=/suggest/address
server.port=${SERVER_PORT:80}
management.health.probes.enabled=true